### ISSUE TITLE
Carry over N2f2 Chain Work

### ISSUE THREAD

**Issue by AndyM84** [zibings/stoic-php-chain#1]
Need to rebuild the chain system(s) from N2f2 here in Stoic.

**Comment by ghost** [comment]
@AndyM84 It seems that composer doesn't allow you to assign the same namespace to multiple directories, so I think we should consider moving the base classes out of the folder and putting them in the top level.

**Comment by ghost** [comment]
@AndyM84 Found two typos when testing...

DispatchBase::makeValid() is missing the underscore when settings $this->_isValid
DispatchBase::isConsumed is missing the underscore when returning $this->_isConsumed
