### ISSUE TITLE
Add Callbacks for Logging Hooks

### ISSUE THREAD

**Issue by AndyM84** [zibings/stoic-php-chain#2]
Need to add the ability to hook callbacks into the ChainHelper class for debugging purposes.  This shouldn't be a concrete dependency on anything like the logging system for Stoic, as then we get a fun little circular dependency to be bothersome.

**Comment by AndyM84** [comment]
Just did the following:

- Added single callback for logging messages (single string argument) to `ChainHelper`
- Added `__toString()` methods to `DispatchBase` and `NodeBase` (can/should be overridden)
- Added `doDebug` toggle to `ChainHelper` so that new `__toString()` methods aren't called every time something happens (minor perf gain when not interested in debug info)

**Comment by ghost** [comment]
This has been added in MR #10, closing this out.
